/* ===========================================================================
   cite.js — COMPATIBILITY MIRROR of ../engine/cite-resolver.js  (DO NOT EDIT).

   Generated by build-corpus.py (the `mirror cite-resolver -> cite.js` step),
   exactly as graph-data.js mirrors graph.json. Kept at this stable path so
   existing consumers that hard-code `corpus/assets/cite.js` keep working:
     - the drishti-graph host (artifacts/koshas-graph/index.html),
     - any note/page that already <script>-loads assets/cite.js.
   Edit the ENGINE file (engine/cite-resolver.js) and re-run the build;
   never hand-edit this copy. Same global `window.Cite`, same contract.
   =========================================================================== */
(function (root) {
  "use strict";

  // Match [[cite: SESSION#TS]] or {quote SESSION#TS} (and {cite ...}).
  var REF_RE = /\[\[\s*cite:\s*([a-z0-9]+)\s*#\s*([0-9:]+)\s*\]\]|\{\s*(?:quote|cite)\s+([a-z0-9]+)\s*#\s*([0-9:]+)\s*\}/gi;

  // Parse "MM:SS" or "H:MM:SS" (or bare seconds) into integer seconds.
  function parseTs(ts) {
    if (ts == null) return null;
    var parts = String(ts).trim().split(":").map(function (p) { return parseInt(p, 10); });
    if (parts.some(isNaN)) return null;
    var sec = 0;
    for (var i = 0; i < parts.length; i++) sec = sec * 60 + parts[i];
    return sec;
  }

  function fmtTime(sec) {
    sec = Math.max(0, Math.floor(sec || 0));
    var h = Math.floor(sec / 3600);
    var m = Math.floor((sec % 3600) / 60);
    var s = sec % 60;
    var pad = function (n) { return n < 10 ? "0" + n : "" + n; };
    return (h > 0 ? h + ":" + pad(m) : m) + ":" + pad(s);
  }

  function ytLink(vid, sec) {
    if (!vid) return null;
    return "https://www.youtube.com/watch?v=" + encodeURIComponent(vid) +
           "&t=" + Math.max(0, Math.floor(sec)) + "s";
  }

  /**
   * Build a resolver bound to one corpus payload.
   * @param {{sessions:Array, cues:Array}} corpus  parsed corpus.json
   */
  function makeResolver(corpus) {
    var sessions = {};
    (corpus.sessions || []).forEach(function (s) { sessions[s.id] = s; });

    // Bucket cues by session, sorted by start time, for fast nearest lookup.
    var bySession = {};
    (corpus.cues || []).forEach(function (c) {
      (bySession[c.s] || (bySession[c.s] = [])).push(c);
    });
    Object.keys(bySession).forEach(function (k) {
      bySession[k].sort(function (a, b) { return a.t - b.t; });
    });

    /**
     * Resolve one reference (see THE CONTRACT above for the return shape).
     */
    function resolve(sessionId, ts) {
      var sec = parseTs(ts);
      var sess = sessions[sessionId];
      var out = {
        ok: false, ref: sessionId + "#" + ts, session: sessionId,
        sessionTitle: sess ? sess.title : null, seconds: sec,
        cue: null, text: null, time: fmtTime(sec), audio: null, reason: null,
      };
      if (!sess) { out.reason = "unknown session '" + sessionId + "'"; return out; }
      if (sec == null) { out.reason = "bad timestamp '" + ts + "'"; return out; }

      var cues = bySession[sessionId] || [];
      if (!cues.length) { out.reason = "no cues for session"; return out; }

      // Prefer the cue whose [t,e] window contains the second.
      var hit = null;
      for (var i = 0; i < cues.length; i++) {
        var c = cues[i];
        var end = (c.e != null) ? c.e : c.t;
        if (sec >= c.t && sec <= end) { hit = c; break; }
        if (c.t > sec) break; // sorted: passed the target
      }
      // Else: nearest cue at/just before the second (or the very first).
      if (!hit) {
        for (var j = 0; j < cues.length; j++) {
          if (cues[j].t <= sec) hit = cues[j]; else break;
        }
        if (!hit) hit = cues[0];
      }

      out.ok = true;
      out.cue = hit;
      out.text = hit.x;
      out.time = fmtTime(hit.t);
      out.seconds = hit.t;
      out.audio = ytLink(sess.vid, hit.t); // null when the session has no vid
      return out;
    }

    /**
     * Find all citation refs in a block of text.
     * @returns {Array<{match,start,end,session,ts}>}
     */
    function findRefs(text) {
      var refs = [];
      var m;
      REF_RE.lastIndex = 0;
      while ((m = REF_RE.exec(text)) !== null) {
        var session = m[1] || m[3];
        var ts = m[2] || m[4];
        refs.push({ match: m[0], start: m.index, end: m.index + m[0].length, session: session, ts: ts });
      }
      return refs;
    }

    return { resolve: resolve, findRefs: findRefs, sessions: sessions };
  }

  var Cite = {
    makeResolver: makeResolver,
    parseTs: parseTs,
    fmtTime: fmtTime,
    ytLink: ytLink,
    REF_RE: REF_RE,
  };

  if (typeof module !== "undefined" && module.exports) module.exports = Cite;
  root.Cite = Cite;
})(typeof window !== "undefined" ? window : this);
